backend/models/File.php
<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "file".
 *
 * @property integer $id
 * @property string $file
 * @property string $title
 */
class File extends FileUpload
{

    public $deleting;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'file';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['file', 'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'file' => 'Файл',
            'title' => 'Описание файла',
            'id' => 'ID',
        ];
    }

    public function afterFind()
    {
        $this->title = json_decode($this->title, 1);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->title = json_encode($this->title);

        $this->file = UploadedFile::getInstance($this, 'file');

        if($this->file){
            $name =  $this->generateName() . '.' . $this->file->extension;
            $this->file->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->file = $name;
        }elseif($this->oldAttributes['file'] && !$this->deleting){
            $this->file = $this->oldAttributes['file'];
        }
        Yii::$app->cacheFrontend->delete('files');


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}

backend/controllers/FileController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\File;
use backend\models\search\File as FileSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * FileController implements the CRUD actions for File model.
 */
class FileController extends FileUploadController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all File models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single File model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    protected function saveTitles($post){
        $t = [];
        foreach ($post['Title'] as $lang=>$item){
            $t[$lang]=$item;
        }
        return $t;
    }

    /**
     * Creates a new File model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new File();

        $post = Yii::$app->request->post();
        if ($model->load($post)){


            $model->title=$this->saveTitles($post);

            if($model->save()) {
                Yii::$app->session->setFlash('success', "Сохраниение прошло успешно");
            }else{
                $errStr = "";
                foreach ($model->getErrors() as $error){
                    $errStr .= "{$error[0]}<br/>";
                }
                Yii::$app->session->setFlash('error', "Исправьте следующие ошибки:<br/>".$errStr);
                return $this->redirect(Yii::$app->request->referrer);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing File model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();

        if ($model->load($post)) {

            $model->title=$this->saveTitles($post);

            if($model->save()) {
                Yii::$app->session->setFlash('success', "Сохраниение прошло успешно");
            }else{
                $errStr = "";
                foreach ($model->getErrors() as $error){
                    $errStr .= "{$error[0]}<br/>";
                }
                Yii::$app->session->setFlash('error', "Исправьте следующие ошибки:<br/>".$errStr);
                return $this->redirect(Yii::$app->request->referrer);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing File model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the File model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return File the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = File::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDelimage($img)
    {
        $arr = explode("|", base64_decode($img));
        $path = Yii::getAlias("@frontend") .'/web/images/' . $arr[0];
        @unlink($path);
        $model = $this->findModel($arr[1]);
        if($arr[2]==1){
             $model->file = "";
             $model->deleting = true;
        }

        $model->save();
        return $this->redirect(['update', 'id' => $model->id]);
    }
}

backend/views/file/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\File */
/* @var $form yii\widgets\ActiveForm */

function is_image($filename) {
    $is = @getimagesize(Yii::getAlias("@frontend").'/web/images/'.$filename);
    if ( !$is ) return false;
    elseif ( !in_array($is[2], array(1,2,3)) ) return false;
  else return true;
}
?>
<?php
$fieldCode="Title";
$fields = "";
foreach (Yii::$app->params['languages'] as $lang){
    $pref = $lang['url'];
    $field = $fieldCode."[".$lang['url']."]";
    $value = (isset($model->title[$pref])) ? $model->title[$pref] : "";
    $col_md = "col-md-".(int)(12/count(Yii::$app->params['languages']));
    $fields .= '
<div class="form-group field-message-message has-success '.$col_md.'">
    <label class="control-label" for="message-message">'.$field.'</label>
    <textarea id="message-message" class="form-control" name="'.$field.'" maxlength="255" rows="6" aria-invalid="false">'.$value.'</textarea>
</div>';
}
?>

<div class="file-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
        <?php
        $html = "<div style='border:2px solid #000; padding:5px;margin-top:5px;margin-bottom:5px'>";
        if($model->file != ''){
            if(is_image($model->file)){
                if(!empty($model->file)) {
                    $html .= "<img src='/images/{$model->file}' alt='' style='max-width: 100%'><br>";
                    $html .= "<a href='" . \yii\helpers\Url::to(["file/delimage", 'img' => base64_encode(implode("|", [$model->file, $model->id, 1]))]) . "'>Удалить</a>";
                }
            }else{
                $html .= "<a download href='/images/{$model->file}'>{$model->file}</a> | ";
                $html .= "<a href='" . \yii\helpers\Url::to(["file/delimage", 'img' => base64_encode(implode("|", [$model->file, $model->id, 1]))]) . "'>Удалить</a>";
            }
        }else{
            $html .= $form->field($model, 'file')->fileInput();
        }

        $html .= "</div>";
        echo $html;

        ?>
        </div>
    </div>

    <?= $fields ?>

    <input type="text" id="title" style="display:none" name="File[title]" value="<?= $model->file ?>" aria-invalid="false">

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/file/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\File */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="file-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'file') ?>

    <?= $form->field($model, 'title') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/file/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\File */

$this->title = 'Добавление';
$this->params['breadcrumbs'][] = ['label' => 'Хранилище файлов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="file-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/file/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\File */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Хранилище файлов';
$this->params['breadcrumbs'][] = $this->title;
function is_image($filename) {
    $is = @getimagesize(Yii::getAlias("@frontend").'/web/images/'.$filename);
    if ( !$is ) return false;
    elseif ( !in_array($is[2], array(1,2,3)) ) return false;
    else return true;
}
?>
<div class="file-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            //'file',
            [
                'attribute' => "file",
                'value' => function($model){

                    $html = '';
                    if(is_image($model->file)){
                        if(!empty($model->file)) {
                            $html .= "<img width='100' src='/images/{$model->file}' alt='' style='max-width: 100%'>";
                        }
                    }else{
                        $html .= "<a download href='/images/{$model->file}'>{$model->file}</a>";
                    }

                    return $html;
                },
                'format' => 'html'
            ],
            [
                'attribute' => "title",
                'value' => function($model){
                    $val = '';
                    foreach ($model->title as $lang=>$msg){
                        $val .= "[{$lang}] ".$msg."<br>";
                    }
                    return $val;
                },
                'format' => 'html'
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/file/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\File */

$this->title = 'Обновление файла: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Хранилище файлов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновление';
?>
<div class="file-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/file/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\File */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="file-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'file',
            'title',
        ],
    ]) ?>

</div>